apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  generation: 1
  labels:
    build: galera-mysql
  name: galera-mysql
  namespace: galera-mysql
spec:
  lookupPolicy:
    local: false